stages:
  complete-ubermedia:
    cmd: dz run-step ubermedia complete
    deps:
    - src/ubermedia/raw_proc.py
    params:
    - zimmer.yaml:
      - envs.complete.params.chunksize_mil
    outs:
    - data/gpsping/ubermedia/complete:
        persist: true
  covid_full_week-ubermedia:
    cmd: dz run-step ubermedia covid_full_week
    deps:
    - data/gpsping/ubermedia/complete
    - src/ubermedia/envs.py
    params:
    - zimmer.yaml:
      - envs.covid_full_week.params.ind_of_weekday
      - envs.covid_full_week.params.is_covid
    outs:
    - data/gpsping/ubermedia/covid_full_week
  covid_saturday-ubermedia:
    cmd: dz run-step ubermedia covid_saturday
    deps:
    - data/gpsping/ubermedia/complete
    - src/ubermedia/envs.py
    params:
    - zimmer.yaml:
      - envs.covid_saturday.params.ind_of_weekday
      - envs.covid_saturday.params.is_covid
    outs:
    - data/gpsping/ubermedia/covid_saturday
  covid_sunday-ubermedia:
    cmd: dz run-step ubermedia covid_sunday
    deps:
    - data/gpsping/ubermedia/complete
    - src/ubermedia/envs.py
    params:
    - zimmer.yaml:
      - envs.covid_sunday.params.ind_of_weekday
      - envs.covid_sunday.params.is_covid
    outs:
    - data/gpsping/ubermedia/covid_sunday
  covid_thursday-ubermedia:
    cmd: dz run-step ubermedia covid_thursday
    deps:
    - data/gpsping/ubermedia/complete
    - src/ubermedia/envs.py
    params:
    - zimmer.yaml:
      - envs.covid_thursday.params.ind_of_weekday
      - envs.covid_thursday.params.is_covid
    outs:
    - data/gpsping/ubermedia/covid_thursday
  covid_tuesday-ubermedia:
    cmd: dz run-step ubermedia covid_tuesday
    deps:
    - data/gpsping/ubermedia/complete
    - src/ubermedia/envs.py
    params:
    - zimmer.yaml:
      - envs.covid_tuesday.params.ind_of_weekday
      - envs.covid_tuesday.params.is_covid
    outs:
    - data/gpsping/ubermedia/covid_tuesday
  non_covid_full_week-ubermedia:
    cmd: dz run-step ubermedia non_covid_full_week
    deps:
    - data/gpsping/ubermedia/complete
    - src/ubermedia/envs.py
    params:
    - zimmer.yaml:
      - envs.non_covid_full_week.params.ind_of_weekday
      - envs.non_covid_full_week.params.is_covid
    outs:
    - data/gpsping/ubermedia/non_covid_full_week
  non_covid_saturday-ubermedia:
    cmd: dz run-step ubermedia non_covid_saturday
    deps:
    - data/gpsping/ubermedia/complete
    - src/ubermedia/envs.py
    params:
    - zimmer.yaml:
      - envs.non_covid_saturday.params.ind_of_weekday
      - envs.non_covid_saturday.params.is_covid
    outs:
    - data/gpsping/ubermedia/non_covid_saturday
  non_covid_sunday-ubermedia:
    cmd: dz run-step ubermedia non_covid_sunday
    deps:
    - data/gpsping/ubermedia/complete
    - src/ubermedia/envs.py
    params:
    - zimmer.yaml:
      - envs.non_covid_sunday.params.ind_of_weekday
      - envs.non_covid_sunday.params.is_covid
    outs:
    - data/gpsping/ubermedia/non_covid_sunday
  non_covid_thursday-ubermedia:
    cmd: dz run-step ubermedia non_covid_thursday
    deps:
    - data/gpsping/ubermedia/complete
    - src/ubermedia/envs.py
    params:
    - zimmer.yaml:
      - envs.non_covid_thursday.params.ind_of_weekday
      - envs.non_covid_thursday.params.is_covid
    outs:
    - data/gpsping/ubermedia/non_covid_thursday
  non_covid_tuesday-ubermedia:
    cmd: dz run-step ubermedia non_covid_tuesday
    deps:
    - data/gpsping/ubermedia/complete
    - src/ubermedia/envs.py
    params:
    - zimmer.yaml:
      - envs.non_covid_tuesday.params.ind_of_weekday
      - envs.non_covid_tuesday.params.is_covid
    outs:
    - data/gpsping/ubermedia/non_covid_tuesday
